# This is the name of the workflow, visible on GitHub UI.
name: build_and_test
on: push
   # branches:
   #    - master

jobs:
  Build-And-Test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
            version: 10
            platform: x64
        
      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Create conan profile
        run: |
          conan profile new default --detect
          conan profile update settings.compiler=clang default 
          conan profile update settings.compiler.version=10 default 
          conan profile update env.CC=/usr/bin/clang default 
          conan profile update env.CXX=/usr/bin/clnag++ default 

      - name: Install googletest
        run: |
          git clone https://github.com/google/googletest.git 
          cd googletest        
          mkdir build          
          cd build
          cmake .. 
          make 
          sudo make install

      - name: Build project
        run: |
          mkdir build
          cd build
          conan install ..
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ls -la
          ./uobject_tests