# This is the name of the workflow, visible on GitHub UI.
name: build_project
on: push
   # branches:
   #    - master

jobs:
    name: Build Project
    runs-on: ubuntu-18.04
  
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
            version: 10
            platform: x64

      - name: Install Eigen
        run:  sudo apt install libeigen3-dev
      
      - name: Install googletest
        run: |
          git clone https://github.com/google/googletest.git -b release-1.11.0
          cd googletest        
          mkdir build          
          cd build
          cmake .. 
          make 
          sudo make install

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          mkdir build
          ./uobject_tests